### ISSUE TITLE
2D detector

### ISSUE THREAD

**Issue by stomachacheGE** [KleinYuan/tf-3d-object-detection#1]
Hi,

Thanks for sharing your project with us. You provided several pre-trained 2D detectors models in your repo. I am curious did you train them by yourself? If not, could you please give me a link to the repo where I can find the source code to train these models?

Thanks a lot :)

Liangcheng

**Comment by KleinYuan** [comment]
@stomachacheGE 
You can refer to this [issue](https://github.com/KleinYuan/tf-object-detection/issues/12#issuecomment-401560705).

You will find the src training code in [here](https://github.com/tensorflow/models/blob/master/research/object_detection/train.py).

**Comment by KleinYuan** [comment]
No follow-up for too long. reopen if this is still an issue.
